controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    
    panda_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_joint_group_controller:
      type: position_controllers/JointGroupPositionController

panda_joint_group_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_finger_joint1
      - panda_finger_joint2