controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    
    panda_joint_state_broadcaster:
      ros__parameters:
        type: joint_state_broadcaster/JointStateBroadcaster

    panda_joint_group_position_controller:
      ros__parameters:
        type: effort_controllers/JointGroupPositionController

panda_joint_group_position_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7